// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.7
// source: program.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Program_GetSupportedCards_FullMethodName = "/program.Program/GetSupportedCards"
	Program_RunCard_FullMethodName           = "/program.Program/RunCard"
)

// ProgramClient is the client API for Program service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProgramClient interface {
	GetSupportedCards(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*Cards, error)
	RunCard(ctx context.Context, in *CardInputWithCardName, opts ...grpc.CallOption) (*structpb.Struct, error)
}

type programClient struct {
	cc grpc.ClientConnInterface
}

func NewProgramClient(cc grpc.ClientConnInterface) ProgramClient {
	return &programClient{cc}
}

func (c *programClient) GetSupportedCards(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*Cards, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cards)
	err := c.cc.Invoke(ctx, Program_GetSupportedCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programClient) RunCard(ctx context.Context, in *CardInputWithCardName, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, Program_RunCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProgramServer is the server API for Program service.
// All implementations must embed UnimplementedProgramServer
// for forward compatibility.
type ProgramServer interface {
	GetSupportedCards(context.Context, *EmptyReq) (*Cards, error)
	RunCard(context.Context, *CardInputWithCardName) (*structpb.Struct, error)
	mustEmbedUnimplementedProgramServer()
}

// UnimplementedProgramServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProgramServer struct{}

func (UnimplementedProgramServer) GetSupportedCards(context.Context, *EmptyReq) (*Cards, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupportedCards not implemented")
}
func (UnimplementedProgramServer) RunCard(context.Context, *CardInputWithCardName) (*structpb.Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCard not implemented")
}
func (UnimplementedProgramServer) mustEmbedUnimplementedProgramServer() {}
func (UnimplementedProgramServer) testEmbeddedByValue()                 {}

// UnsafeProgramServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProgramServer will
// result in compilation errors.
type UnsafeProgramServer interface {
	mustEmbedUnimplementedProgramServer()
}

func RegisterProgramServer(s grpc.ServiceRegistrar, srv ProgramServer) {
	// If the following call pancis, it indicates UnimplementedProgramServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Program_ServiceDesc, srv)
}

func _Program_GetSupportedCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServer).GetSupportedCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Program_GetSupportedCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServer).GetSupportedCards(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Program_RunCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardInputWithCardName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServer).RunCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Program_RunCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServer).RunCard(ctx, req.(*CardInputWithCardName))
	}
	return interceptor(ctx, in, info, handler)
}

// Program_ServiceDesc is the grpc.ServiceDesc for Program service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Program_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "program.Program",
	HandlerType: (*ProgramServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSupportedCards",
			Handler:    _Program_GetSupportedCards_Handler,
		},
		{
			MethodName: "RunCard",
			Handler:    _Program_RunCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "program.proto",
}
