// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: program.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	In            *structpb.Struct       `protobuf:"bytes,2,opt,name=in,proto3" json:"in,omitempty"`
	Out           *structpb.Struct       `protobuf:"bytes,3,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_program_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Card) GetIn() *structpb.Struct {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Card) GetOut() *structpb.Struct {
	if x != nil {
		return x.Out
	}
	return nil
}

type Cards struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cards) Reset() {
	*x = Cards{}
	mi := &file_program_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cards) ProtoMessage() {}

func (x *Cards) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cards.ProtoReflect.Descriptor instead.
func (*Cards) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{1}
}

func (x *Cards) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type EmptyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReq) Reset() {
	*x = EmptyReq{}
	mi := &file_program_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReq) ProtoMessage() {}

func (x *EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReq.ProtoReflect.Descriptor instead.
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{2}
}

type CardInputWithCardName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          string                 `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	Input         *structpb.Struct       `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardInputWithCardName) Reset() {
	*x = CardInputWithCardName{}
	mi := &file_program_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardInputWithCardName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardInputWithCardName) ProtoMessage() {}

func (x *CardInputWithCardName) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardInputWithCardName.ProtoReflect.Descriptor instead.
func (*CardInputWithCardName) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{3}
}

func (x *CardInputWithCardName) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

func (x *CardInputWithCardName) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

var File_program_proto protoreflect.FileDescriptor

const file_program_proto_rawDesc = "" +
	"\n" +
	"\rprogram.proto\x12\aprogram\x1a\x1cgoogle/protobuf/struct.proto\"n\n" +
	"\x04Card\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x02in\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x02in\x12)\n" +
	"\x03out\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x03out\",\n" +
	"\x05Cards\x12#\n" +
	"\x05cards\x18\x01 \x03(\v2\r.program.CardR\x05cards\"\n" +
	"\n" +
	"\bEmptyReq\"Z\n" +
	"\x15CardInputWithCardName\x12\x12\n" +
	"\x04card\x18\x01 \x01(\tR\x04card\x12-\n" +
	"\x05input\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05input2\x85\x01\n" +
	"\aProgram\x126\n" +
	"\x11GetSupportedCards\x12\x11.program.EmptyReq\x1a\x0e.program.Cards\x12B\n" +
	"\aRunCard\x12\x1e.program.CardInputWithCardName\x1a\x17.google.protobuf.StructB3Z1github.com/ondbyte/pipeman/internal/protos/protosb\x06proto3"

var (
	file_program_proto_rawDescOnce sync.Once
	file_program_proto_rawDescData []byte
)

func file_program_proto_rawDescGZIP() []byte {
	file_program_proto_rawDescOnce.Do(func() {
		file_program_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_program_proto_rawDesc), len(file_program_proto_rawDesc)))
	})
	return file_program_proto_rawDescData
}

var file_program_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_program_proto_goTypes = []any{
	(*Card)(nil),                  // 0: program.Card
	(*Cards)(nil),                 // 1: program.Cards
	(*EmptyReq)(nil),              // 2: program.EmptyReq
	(*CardInputWithCardName)(nil), // 3: program.CardInputWithCardName
	(*structpb.Struct)(nil),       // 4: google.protobuf.Struct
}
var file_program_proto_depIdxs = []int32{
	4, // 0: program.Card.in:type_name -> google.protobuf.Struct
	4, // 1: program.Card.out:type_name -> google.protobuf.Struct
	0, // 2: program.Cards.cards:type_name -> program.Card
	4, // 3: program.CardInputWithCardName.input:type_name -> google.protobuf.Struct
	2, // 4: program.Program.GetSupportedCards:input_type -> program.EmptyReq
	3, // 5: program.Program.RunCard:input_type -> program.CardInputWithCardName
	1, // 6: program.Program.GetSupportedCards:output_type -> program.Cards
	4, // 7: program.Program.RunCard:output_type -> google.protobuf.Struct
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_program_proto_init() }
func file_program_proto_init() {
	if File_program_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_program_proto_rawDesc), len(file_program_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_program_proto_goTypes,
		DependencyIndexes: file_program_proto_depIdxs,
		MessageInfos:      file_program_proto_msgTypes,
	}.Build()
	File_program_proto = out.File
	file_program_proto_goTypes = nil
	file_program_proto_depIdxs = nil
}
